[package]
authors = ["Luqman Aden <me@luqman.ca>"]
name = "gdax-client"
version = "0.1.0"

[dependencies]
aster = "0.36.0"
base64 = "0.2.1"
hyper = "0.9.14"
rust-crypto = "0.2.36"
serde = "0.8.20"
serde_derive = "0.8.20"
serde_json = "0.8.4"
time = "0.1.35"

[dependencies.chrono]
features = ["serde"]
version = "0.2.25"

[dependencies.uuid]
features = ["serde"]
version = "0.3.1"

[dev-dependencies]
env_logger = "0.3"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.3.1"
